name: Release

on:
  workflow_dispatch:
  
jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      contents: write
    uses: ./.github/workflows/build_internal.yml
    with: 
      createrelease: true
  